using System;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Threading.Tasks;

namespace ToreAurstadIT.DapperUtils.Docs
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var dapperUtilsAssembly = Assembly.LoadFrom("ToreAurstadIT.DapperUtils.Docs.exe");

            Console.WriteLine($"Detecting assembly version of ToreAurstadIT.DapperUtils.Docs.exe: {dapperUtilsAssembly.GetName().Version}");
            Console.WriteLine("Generating markdown files..");
            string curDir = Directory.GetCurrentDirectory();
            if (!Directory.Exists(Path.Combine(curDir, "md")))
            {
                Directory.CreateDirectory(Path.Combine(curDir, "md"));
            }
            Process.Start(Path.Combine(curDir,"MarkdownGenerator.exe"), "ToreAurstadIT.DapperUtils.Docs.exe md");
            Console.WriteLine("Opening folder of markdown files which was generated by MarkdownGenerator..");
            Process.Start(Path.Combine(Directory.GetCurrentDirectory(), "md"));
            Console.WriteLine("Press any key to continue.. Exiting in ten seconds.");
            await Task.Delay(10*1000);
        }
    }
}
